"""
Messages printed out below the grader.check cell
"""

# The message to print above any feedback generated by the LLM
LLM_FEEDBACK_SECTION_HEADER = "Potentially helpful AI-generated feedback:"

LLM_RATE_LIMIT_MSG = (
    "You have made too many requests in a short period. "
    "Please wait 30 seconds before trying again."
)

# Gets printed when anything goes wrong with accessing the gpt220 service
GET_LLM_FEEDBACK_FAILED_MSG = """Error, failed to reach server for feedback.
This will not affect your grade. Please continue working on the assignment
and notify course staff about this issue."""

# The message format to print immediately after grader.check is called. Formatted with q_id
CHECK_START_FORMAT = (
    "Make sure you saved the notebook before running this cell. Running check for {}..."
)

# Appears whenever student grader could not find q_id in assignment metadata
FAILED_FIND_QID_IN_METADATA_FORMAT = """Could not find key {} in {}.
Please make sure you have not modified this grader.check cell or the metadata file.
If you haven't modified this grader.check cell, try re-downloading the metadata file.
Seek assistance from course staff afterward if you are still running into issues."""

# Appears whenever grader check could not find code cell for a question
NO_CODE_FOR_QID_FORMAT = """Could not find cell with tag {}-code
in your notebook. Please make sure that the code you have written for this
question has this tag on it. You can add a tag to a cell from the settings
panel on the right."""

# The message to print below any errors or warnings that resulted from
# running cells above the current question
ISSUES_ABOVE_MSG = "\nThere are issues in the cells above this question. These must be resolved before this check can run."

# Appears at start of bullet point in errors section to prefix exceptions caused by student code.
# Example: - Exception occurred: invalid syntax (<string>, line 1)
CUR_QUESTION_ERROR_PREFIX = "Exception occurred: "

# The message format to print in the errors section when a student has
# not defined a required variable.
MISSED_REQ_VAR_FORMAT = "Student code does not define required variable: {}"

# The message format to print in the errors section when a student has
# not called a required function
MISSED_REQ_FUNC_FORMAT = "Student code does not use: {}"

# Appears at start of bullet point in errors section before the assertion
# error message. Example: - Test case failed: division by zero
ASSERTION_FAILED_PREFIX = "Test case failed: "

# The message to print when the student's code for a question meets all requirements
SUCCESS_MSG = "Great job! You passed all test cases for this question."

# Appears at start of bullet point in errors section when an error occured
# in an above cell. Example: - Error in above cell: division by zero
ABOVE_QUESTION_ERROR_PREFIX = "Error in above cell: "
